import { ReactNode } from "react";
import "./globals.css";
import Header from "@/components/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center">
        <Header />
        <div className="px-4 md:px-8 w-full">{children}</div>
      </body>
    </html>
  );
}
